version: "3"
services:
  springdbapp:
    image: springcrudapp
    ports:
      - "5000:8080"
    networks:
      - crdapp-network
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql57-data
    ports:
      - "3308:3306"
    networks:
      - crdapp-network
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpassword

networks:
  crdapp-network: 
